"""
Validator Agent for testing and verification.

The Validator agent is responsible for the verification phase:
- Running tests on migrated code
- Validating semantic preservation
- Comparing test counts (before/after)
- Generating validation reports
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from src.agents.base import AgentResult, BaseAgent
from src.agents.validator.docker_runner import (
    DockerRunner,
    LocalRunner,
    TestResult,
)
from src.shared.logger import get_logger
from src.tmg import TypedMigrationGraph
from src.tmg.models import MigrationProposal, NodeState

logger = get_logger(__name__, component="validator")


@dataclass
class ValidationReport:
    """
    Report generated by the Validator agent.
    
    Attributes:
        project_path: Path to the validated project.
        test_result: Result from running tests.
        before_test_count: Test count before migration.
        after_test_count: Test count after migration.
        semantic_preserved: Whether tests indicate behavior preservation.
        compilation_success: Whether the code compiles.
        approval_recommendation: Recommended approval status.
        issues: List of identified issues.
    """
    project_path: str
    test_result: TestResult | None = None
    before_test_count: int = 0
    after_test_count: int = 0
    semantic_preserved: bool = False
    compilation_success: bool = False
    approval_recommendation: str = "unknown"
    issues: list[str] = field(default_factory=list)
    proposals_validated: list[dict[str, Any]] = field(default_factory=list)
    
    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "project_path": self.project_path,
            "test_result": self.test_result.to_dict() if self.test_result else None,
            "before_test_count": self.before_test_count,
            "after_test_count": self.after_test_count,
            "semantic_preserved": self.semantic_preserved,
            "compilation_success": self.compilation_success,
            "approval_recommendation": self.approval_recommendation,
            "issues": self.issues,
            "proposals_validated": self.proposals_validated,
        }


class ValidatorAgent(BaseAgent):
    """
    Agent responsible for validating migrated code.
    
    The Validator runs tests and verifies that migrated code:
    - Compiles successfully
    - Passes all existing tests
    - Maintains test count (no tests lost)
    - Preserves semantic behavior
    
    Attributes:
        docker_runner: Docker runner for isolated test execution.
        local_runner: Fallback local runner.
        use_docker: Whether to prefer Docker execution.
    
    Example:
        >>> tmg = TypedMigrationGraph(name="MyProject")
        >>> agent = ValidatorAgent(tmg=tmg)
        >>> result = agent.execute(project_path="/path/to/project")
        >>> print(f"Tests passed: {result.data.test_result.passed_count}")
    """
    
    def __init__(
        self,
        tmg: TypedMigrationGraph | None = None,
        use_docker: bool = True,
    ) -> None:
        """
        Initialize the Validator agent.
        
        Args:
            tmg: The Typed Migration Graph.
            use_docker: Whether to prefer Docker for execution.
        """
        super().__init__(name="Validator", tmg=tmg)
        self.docker_runner = DockerRunner()
        self.local_runner = LocalRunner()
        self.use_docker = use_docker
        self._baseline_results: dict[str, TestResult] = {}
    
    def process(
        self,
        project_path: str,
        proposals: list[MigrationProposal] | None = None,
        establish_baseline: bool = False,
        **kwargs: Any,
    ) -> AgentResult[ValidationReport]:
        """
        Validate a project or migration proposals.
        
        Args:
            project_path: Path to the Maven project.
            proposals: Optional list of migration proposals to validate.
            establish_baseline: If True, record baseline test counts.
            **kwargs: Additional arguments.
            
        Returns:
            AgentResult containing ValidationReport.
        """
        project_path_obj = Path(project_path)
        
        if not project_path_obj.exists():
            return AgentResult(
                success=False,
                error=f"Project path does not exist: {project_path}",
            )
        
        self.logger.info(
            "validation_started",
            project=str(project_path_obj),
            establish_baseline=establish_baseline,
            has_proposals=proposals is not None,
        )
        
        report = ValidationReport(project_path=str(project_path_obj))
        
        # Run tests
        test_result = self._run_tests(project_path_obj)
        report.test_result = test_result
        report.compilation_success = "COMPILATION ERROR" not in test_result.stdout
        report.after_test_count = test_result.test_count
        
        # Handle baseline establishment
        if establish_baseline:
            self._baseline_results[str(project_path_obj)] = test_result
            report.before_test_count = test_result.test_count
            self.logger.info(
                "baseline_established",
                test_count=test_result.test_count,
            )
        else:
            # Compare with baseline if available
            baseline = self._baseline_results.get(str(project_path_obj))
            if baseline:
                report.before_test_count = baseline.test_count
                report.semantic_preserved = self._check_semantic_preservation(
                    baseline, test_result
                )
        
        # Validate proposals if provided
        if proposals:
            for proposal in proposals:
                validation = self._validate_proposal(proposal, test_result)
                report.proposals_validated.append(validation)
        
        # Determine recommendation
        report.approval_recommendation = self._determine_recommendation(report)
        
        # Collect issues
        report.issues = self._collect_issues(report, test_result)
        
        self.logger.info(
            "validation_complete",
            success=test_result.success,
            tests_run=test_result.test_count,
            passed=test_result.passed_count,
            failed=test_result.failed_count,
            recommendation=report.approval_recommendation,
        )
        
        return AgentResult(
            success=True,
            data=report,
            metadata={
                "docker_used": self.use_docker and self.docker_runner.is_docker_available(),
            },
        )
    
    def _run_tests(self, project_path: Path) -> TestResult:
        """
        Run tests using Docker or local Maven.
        
        Args:
            project_path: Path to the project.
            
        Returns:
            TestResult from the test run.
        """
        if self.use_docker and self.docker_runner.is_docker_available():
            self.logger.debug("using_docker_runner")
            return self.docker_runner.run_maven_verify(project_path)
        elif self.local_runner.is_maven_available():
            self.logger.debug("using_local_runner")
            return self.local_runner.run_maven_verify(project_path)
        else:
            self.logger.warning("no_runner_available")
            return TestResult(
                success=False,
                error_message="Neither Docker nor local Maven is available",
            )
    
    def _check_semantic_preservation(
        self,
        before: TestResult,
        after: TestResult,
    ) -> bool:
        """
        Check if semantic behavior is preserved.
        
        Criteria:
        - Test count should not decrease
        - Pass rate should not significantly decrease
        
        Args:
            before: Test results before migration.
            after: Test results after migration.
            
        Returns:
            True if semantics appear preserved.
        """
        # Test count should not decrease
        if after.test_count < before.test_count:
            self.logger.warning(
                "test_count_decreased",
                before=before.test_count,
                after=after.test_count,
            )
            return False
        
        # Pass rate check
        before_pass_rate = (
            before.passed_count / before.test_count 
            if before.test_count > 0 else 1.0
        )
        after_pass_rate = (
            after.passed_count / after.test_count 
            if after.test_count > 0 else 1.0
        )
        
        # Allow some tolerance (5%)
        if after_pass_rate < before_pass_rate - 0.05:
            self.logger.warning(
                "pass_rate_decreased",
                before=before_pass_rate,
                after=after_pass_rate,
            )
            return False
        
        return True
    
    def _validate_proposal(
        self,
        proposal: MigrationProposal,
        test_result: TestResult,
    ) -> dict[str, Any]:
        """
        Validate a single migration proposal.
        
        Args:
            proposal: The proposal to validate.
            test_result: Current test results.
            
        Returns:
            Validation result dictionary.
        """
        validation = {
            "node_id": proposal.node_id,
            "original_confidence": proposal.confidence,
            "validated": False,
            "validation_score": 0.0,
            "issues": [],
        }
        
        # Check if proposal's confidence matches test results
        if test_result.success:
            validation["validated"] = True
            validation["validation_score"] = min(1.0, proposal.confidence + 0.1)
        else:
            validation["issues"].append("Tests failed after applying proposal")
            validation["validation_score"] = max(0.0, proposal.confidence - 0.3)
        
        return validation
    
    def _determine_recommendation(self, report: ValidationReport) -> str:
        """
        Determine approval recommendation based on validation.
        
        Args:
            report: The validation report.
            
        Returns:
            Recommendation string.
        """
        if not report.compilation_success:
            return "reject"
        
        if report.test_result and report.test_result.success:
            if report.semantic_preserved or report.before_test_count == 0:
                return "approve"
            else:
                return "approve_with_review"
        
        if report.test_result and report.test_result.failed_count > 0:
            if report.test_result.failed_count <= 2:
                return "approve_with_review"
            else:
                return "reject"
        
        return "needs_review"
    
    def _collect_issues(
        self,
        report: ValidationReport,
        test_result: TestResult,
    ) -> list[str]:
        """Collect all identified issues."""
        issues = []
        
        if not report.compilation_success:
            issues.append("Compilation failed")
        
        if test_result.failed_count > 0:
            issues.append(f"{test_result.failed_count} tests failed")
        
        if report.before_test_count > 0 and report.after_test_count < report.before_test_count:
            issues.append(
                f"Test count decreased: {report.before_test_count} -> {report.after_test_count}"
            )
        
        if test_result.error_message:
            issues.append(test_result.error_message)
        
        return issues
    
    def transition_to_migrated(self, node_ids: list[str]) -> int:
        """
        Transition validated nodes to MIGRATED state.
        
        Args:
            node_ids: List of node IDs to transition.
            
        Returns:
            Number of nodes transitioned.
        """
        count = 0
        for node_id in node_ids:
            try:
                node = self.tmg.get_node(node_id)
                if node.state == NodeState.DEPRECATED:
                    self.tmg.transition_state(node_id, NodeState.MIGRATED)
                    count += 1
            except Exception as e:
                self.logger.warning(
                    "transition_failed",
                    node_id=node_id,
                    error=str(e),
                )
        
        self.logger.info("nodes_migrated", count=count)
        return count
    
    def sign_proposal(
        self,
        proposal: MigrationProposal,
        approval: bool,
        comments: str = "",
    ) -> dict[str, Any]:
        """
        Sign a migration proposal as part of consensus.
        
        Args:
            proposal: The proposal to sign.
            approval: Whether to approve.
            comments: Optional comments.
            
        Returns:
            Signature dictionary.
        """
        from datetime import datetime
        
        signature = {
            "agent": self.name,
            "node_id": proposal.node_id,
            "approval": approval,
            "timestamp": datetime.now().isoformat(),
            "comments": comments,
        }
        
        self.logger.info(
            "proposal_signed",
            node_id=proposal.node_id,
            approval=approval,
        )
        
        return signature
