"""
Archeologist Agent for code analysis and TMG population.

The Archeologist agent is responsible for the static analysis phase:
- Parsing Java source files
- Extracting structural information
- Populating the TMG with nodes and edges
- Identifying deprecated APIs
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from src.agents.base import AgentResult, BaseAgent
from src.agents.archeologist.parser import JavaParser, ParseResult
from src.shared.logger import get_logger
from src.shared.tmg import TypedMigrationGraph
from src.shared.tmg.models import NodeState

logger = get_logger(__name__, component="archeologist")


@dataclass
class AnalysisReport:
    """
    Report generated by the Archeologist agent.
    
    Attributes:
        repository_path: Path to the analyzed repository.
        files_analyzed: Number of Java files processed.
        total_nodes: Total TMG nodes created.
        total_edges: Total TMG edges created.
        deprecated_apis: Count of deprecated API usages found.
        parse_errors: List of files that failed to parse.
        statistics: Detailed breakdown by node type.
    """
    repository_path: str
    files_analyzed: int = 0
    total_nodes: int = 0
    total_edges: int = 0
    deprecated_apis: int = 0
    parse_errors: list[str] = field(default_factory=list)
    statistics: dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> dict[str, Any]:
        """Convert report to dictionary."""
        return {
            "repository_path": self.repository_path,
            "files_analyzed": self.files_analyzed,
            "total_nodes": self.total_nodes,
            "total_edges": self.total_edges,
            "deprecated_apis": self.deprecated_apis,
            "parse_errors": self.parse_errors,
            "statistics": self.statistics,
        }


class ArcheologistAgent(BaseAgent):
    """
    Agent responsible for analyzing Java codebases and populating the TMG.
    
    The Archeologist performs static analysis on Java source files,
    extracting structural information and building the Typed Migration
    Graph that serves as the shared state for all agents.
    
    Key responsibilities:
    - Parse Java source files using javalang
    - Create TMG nodes for classes, methods, fields
    - Create TMG edges for dependencies
    - Identify deprecated Java 8 APIs
    - Transition analyzed nodes to ANALYZED state
    
    Attributes:
        parser: The JavaParser instance used for parsing.
    
    Example:
        >>> tmg = TypedMigrationGraph(name="MyProject")
        >>> agent = ArcheologistAgent(tmg=tmg)
        >>> result = agent.execute(repository_path="/path/to/repo")
        >>> print(f"Analyzed {result.data.files_analyzed} files")
    """
    
    def __init__(
        self,
        tmg: TypedMigrationGraph | None = None,
        source_version: str = "8",
        target_version: str = "17",
    ) -> None:
        """
        Initialize the Archeologist agent.
        
        Args:
            tmg: The Typed Migration Graph to populate.
            source_version: Source Java version.
            target_version: Target Java version.
        """
        super().__init__(name="Archeologist", tmg=tmg)
        self.parser = JavaParser(
            source_version=source_version,
            target_version=target_version,
        )
        self.source_version = source_version
        self.target_version = target_version
    
    def process(
        self,
        repository_path: str,
        recursive: bool = True,
        **kwargs: Any,
    ) -> AgentResult[AnalysisReport]:
        """
        Analyze a Java repository and populate the TMG.
        
        Args:
            repository_path: Path to the Java repository to analyze.
            recursive: Whether to recursively search subdirectories.
            **kwargs: Additional arguments (unused).
            
        Returns:
            AgentResult containing the AnalysisReport.
        """
        repo_path = Path(repository_path)
        
        if not repo_path.exists():
            return AgentResult(
                success=False,
                error=f"Repository path does not exist: {repository_path}",
            )
        
        self.logger.info(
            "analysis_started",
            repository=str(repo_path),
            source_version=self.source_version,
            target_version=self.target_version,
        )
        
        # Initialize report
        report = AnalysisReport(repository_path=str(repo_path))
        
        # Parse all Java files
        parse_results = self.parser.parse_directory(repo_path, recursive=recursive)
        report.files_analyzed = len(parse_results)
        
        # Process parse results and populate TMG
        for parse_result in parse_results:
            self._process_parse_result(parse_result, report)
        
        # Transition all new nodes to ANALYZED state
        analyzed_count = self._transition_nodes_to_analyzed()
        
        # Compile statistics
        report.statistics = self._compile_statistics()
        
        self.logger.info(
            "analysis_complete",
            files_analyzed=report.files_analyzed,
            total_nodes=report.total_nodes,
            total_edges=report.total_edges,
            deprecated_apis=report.deprecated_apis,
            errors=len(report.parse_errors),
        )
        
        return AgentResult(
            success=True,
            data=report,
            metadata={
                "nodes_analyzed": analyzed_count,
                "tmg_name": self.tmg.name,
            },
        )
    
    def _process_parse_result(
        self,
        parse_result: ParseResult,
        report: AnalysisReport,
    ) -> None:
        """
        Process a single file's parse result and add to TMG.
        
        Args:
            parse_result: The ParseResult from the parser.
            report: The analysis report to update.
        """
        # Collect errors
        report.parse_errors.extend(parse_result.errors)
        
        # Add nodes to TMG
        for node in parse_result.nodes:
            try:
                if not self.tmg.has_node(node.id):
                    self.tmg.add_node(node)
                    report.total_nodes += 1
                    
                    # Count deprecated APIs
                    if node.metadata.get("deprecated"):
                        report.deprecated_apis += 1
            except ValueError as e:
                self.logger.debug("duplicate_node", node_id=node.id, error=str(e))
        
        # Add edges to TMG
        for edge in parse_result.edges:
            try:
                # Only add edge if both nodes exist
                if self.tmg.has_node(edge.source) and self.tmg.has_node(edge.target):
                    if self.tmg.get_edge(edge.source, edge.target) is None:
                        self.tmg.add_edge(edge)
                        report.total_edges += 1
            except Exception as e:
                self.logger.debug(
                    "edge_skipped",
                    source=edge.source,
                    target=edge.target,
                    error=str(e),
                )
    
    def _transition_nodes_to_analyzed(self) -> int:
        """
        Transition all UNPROCESSED nodes to ANALYZED.
        
        Returns:
            Number of nodes transitioned.
        """
        unprocessed_nodes = self.tmg.get_nodes_by_state(NodeState.UNPROCESSED)
        count = 0
        
        for node in unprocessed_nodes:
            try:
                self.tmg.transition_state(node.id, NodeState.ANALYZED)
                count += 1
            except Exception as e:
                self.logger.warning(
                    "transition_failed",
                    node_id=node.id,
                    error=str(e),
                )
        
        self.logger.info("nodes_transitioned", count=count, new_state="ANALYZED")
        return count
    
    def _compile_statistics(self) -> dict[str, Any]:
        """
        Compile statistics from the TMG.
        
        Returns:
            Dictionary of statistics.
        """
        stats = self.tmg.get_stats()
        
        # Add additional analysis-specific stats
        cycles = self.tmg.find_cycles()
        if cycles:
            stats["cycles"] = [list(c) for c in cycles[:10]]  # Limit to first 10
            stats["cycle_warning"] = (
                f"Found {len(cycles)} cycles in dependency graph. "
                "These may cause LLM hallucination issues."
            )
        
        return stats
    
    def get_deprecated_nodes(self) -> list[dict[str, Any]]:
        """
        Get all nodes that use deprecated APIs.
        
        Returns:
            List of node info dictionaries.
        """
        deprecated = []
        for node in self.tmg:
            if node.metadata.get("deprecated"):
                deprecated.append({
                    "id": node.id,
                    "name": node.name,
                    "type": node.node_type.name,
                    "file": node.file_path,
                    "line": node.line_start,
                    "replacement": node.metadata.get("replacement", "Unknown"),
                })
        return deprecated
